# light base image
FROM node:22.4-alpine  

#static instructions higher in the order
WORKDIR /app
EXPOSE 3000
COPY run-migrations.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/run-migrations.sh
ENTRYPOINT ["run-migrations.sh"]
CMD ["npm", "start"]

#dynamic instruction lower in the order. 
COPY package*.json ./
RUN npm install
COPY . .

